//TODO: Implement this sometime in the future 

//WARNING, WHEN ADDING, YOU NEED TO ADD NEW ENUM IN EnumType ADD NEW EnumId ENUM IN TheModifierIdentifierEnums!!
//ON TOP OF THAT, YOU NEED TO ADD ANOTHER CASE TO IModifiersCollection FILE
//YOU NEED TO POINT OUT TO SPECIFIC VARIABLE IN CASE OF THAT EnumId, SO YOU PROBABLY NEED TO CREATE NEW IN ALLOBJECTINFORMATION
//ALSO, TO BE ABLE TO DO THAT EDIT EQUIPMENT SCRIPT TOO, ADD ENUMS VARIABLE FOR NEW ONE AND ADD CASE FOR IT


